### PR TITLE
docs: add document guide for grafana/influxdb setup

### PR DESCRIPTION
**Pull request by hadv**
In this tutorial, we'll set up your Opera client to push data to **InfluxDB** to create a database and **Grafana** to create a graph visualisation of the data. Doing it manually will help you understand the process better, alter it, and deploy in different environments.

### CODE REVIEW

**Comment by uprendis** [comment]
It may be better to push into the wiki repo

**Comment by hadv** [comment]
> It may be better to push into the wiki repo

okay, I put into wiki page here

https://github.com/Fantom-foundation/go-opera/wiki/Grafana

**Comment by huahuayu** [comment]
Hi I have read the wiki, do you have dashboard which use Prometheus as datasource?

**Comment by hadv** [comment]
Hi @huahuayu

I make a docker compose for prometheus on this repo: https://github.com/hadv/fantom-prometheus to use on my local machine.

You can take it as reference, hope this will help!

**Comment by huahuayu** [comment]
@hadv Thanks, this will be helpful, but in https://github.com/hadv/fantom-prometheus  there's no `dashborad.json` file included?

**Comment by huahuayu** [comment]
> okay, I put into wiki page here
> https://github.com/Fantom-foundation/go-opera/wiki/Grafana

hi @hadv if I have several different go-opera nodes, all of them push the metrics to the same infuxDb, is it ok or not? How to differentiate them from each other?

**Comment by hadv** [comment]
> hi @hadv if I have several different go-opera nodes, all of them push the metrics to the same infuxDb, is it ok or not? How to differentiate them from each other?

@huahuayu You can use this flag `--metrics.influxdb.tags` to set difference tags/value for difference nodes then you can filter the metrics by tags on Grafana dashboard for each node separately.

The default value for is `--metrics.influxdb.tags` flag is `"host=localhost"`, you need to specify difference value for each nodes and _notice that there's an issue related to tags with **InfluxDB 1.6.4** on **Ubuntu** then I think it better to use **Debian** to avoid the issue_

https://github.com/influxdata/influxdb/issues/9953#issuecomment-643012845

**Pull request closed without merging**
