### PR TITLE
Update contracts bytecodes

### PR DESCRIPTION
**Pull request by mprishchepo**
The list of last changes:
- ABI and byte code of contracts located in gossib/contracts and opera/contracts from branch "develop" of opera-sfc repository were updated.
- The SFCLib contract was added to genesis builder at 0xfc01face00000000000000000000000000000000 address.
- The arguments list of initializeAll instruction of NetworkInitializer contract were updated.
- Some arising errors in tests were fixed by increasing of transaction gasPrice.

### CODE REVIEW

**Comment by uprendis** [comment]
Hello @mprishchepo,
Good day to you!
Please make sure that bytecode was generated with `make` command in `opera-sfc` repo. This command does it via a docker container so that resulting bytecode would be reproducible
There's no need to preserve old versions of bytecode, you can leave just the latest one. It influences only fakenet anyway, as testnet/mainnet genesis-es are already generated. In a case of some tests fail with latest bytecode, then please let me know and I'll take a look

**Comment by IntegralTeam** [comment]
1. Bytecodes are generated using `go generate ./gossip/sfc_test.go` command. This command calls the scripts described at the beginning of the sfc_test.go file, and in this file the build goes inside the nodejs container.
-  Bytecodes of contracts generated with the go generate ./gossip/sfc_test.go command MATCH those bytecode generated with the `make` command.
2. The bytecode versions have already been updated, and we do not store old bytecode versions here.

**Comment by mprishchepo** [comment]
Hello @uprendis!

1.  Bytecodes are generated using `go generate ./gossip/sfc_test.go` command. This command calls the scripts described at the beginning of the sfc\_test.go file, and in this file the build goes inside the nodejs container.
- Bytecodes of contracts generated with the `go generate ./gossip/sfc\_test.go` command MATCH those bytecode generated with the `make` command.

2.  The bytecode versions have already been updated, and we do not store old bytecode versions here.

**Comment by uprendis** [comment]
> The bytecode versions have already been updated, and we do not store old bytecode versions here.

I mean files like gossip/contract/driver100/contract.go

**Pull request merged**
